### ISSUE TITLE
How to display splash art as picture?

### ISSUE THREAD

**Issue by ghost** [Ponita0/PoniLCU#17]
Example:
**Json data**
`"baseSplashPath": "/lol-game-data/assets/v1/champion-splashes/10/10000.jpg"`
**Winform Button**
`button1.Image = ???`

**Comment by Ponita0** [comment]
This is an example url of the same photo u sent 
https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-splashes/10/10000.jpg
![](https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-splashes/10/10000.jpg)

**Comment by ghost** [comment]
Is this resource official?

**Comment by Ponita0** [comment]
Not official, but reliable.. i can send the official one too if u want

Yours...
Ibrahim
________________________________

**Comment by Ponita0** [comment]
well, imma close it now... if u needed any more help just reopen
